/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/nBsP81TAG1NrRvi6/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#b3d4b2']} />
      <group {...props} dispose={null}>
        <pointLight
          name="Point Light 3"
          intensity={1.5}
          distance={205}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={100}
          shadow-camera-far={2000}
          color="#fed500"
          position={[73.39, 6, -1.01]}
        />
        <pointLight
          name="Point Light 2"
          intensity={1.5}
          distance={205}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={100}
          shadow-camera-far={2000}
          color="#fed500"
          position={[73.39, 6, -1.01]}
        />
        <directionalLight
          name="Directional Light 2"
          intensity={0.3}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={1}
          shadow-camera-far={2500}
          shadow-camera-left={-1250}
          shadow-camera-right={1250}
          shadow-camera-top={1250}
          shadow-camera-bottom={-1250}
          color="#8ec1fe"
          position={[530.26, 187.64, 274.71]}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.6}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={1}
          shadow-camera-far={3400}
          shadow-camera-left={-350}
          shadow-camera-right={350}
          shadow-camera-top={350}
          shadow-camera-bottom={-350}
          color="#cde5fe"
          position={[-280.4, 372.28, 569.66]}
        />
        <group name="Bed Table" position={[72.66, -41.86, -0.21]}>
          <mesh
            name="Sphere 2"
            geometry={nodes['Sphere 2'].geometry}
            material={materials['Sphere 2 Material']}
            castShadow
            receiveShadow
            position={[72.55, -52.21, 19.5]}
            rotation={[0, -0.02, 0]}
            scale={0.23}
          />
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials['Sphere Material']}
            castShadow
            receiveShadow
            position={[72.55, -33.62, 19.5]}
            rotation={[0, -0.02, 0]}
            scale={0.23}
          />
          <mesh
            name="Cube 61"
            geometry={nodes['Cube 61'].geometry}
            material={materials['Cube 61 Material']}
            castShadow
            receiveShadow
            position={[72.41, -51.74, 12.67]}
            rotation={[0, -0.02, 0]}
            scale={[0.84, 0.34, 0.25]}
          />
          <mesh
            name="Cube 60"
            geometry={nodes['Cube 60'].geometry}
            material={materials['Cube 60 Material']}
            castShadow
            receiveShadow
            position={[72.41, -32.93, 12.67]}
            rotation={[0, -0.02, 0]}
            scale={[0.84, 0.34, 0.25]}
          />
          <mesh
            name="Cube 59"
            geometry={nodes['Cube 59'].geometry}
            material={materials['Cube 59 Material']}
            castShadow
            receiveShadow
            position={[72.66, -41.86, -1.36]}
            rotation={[0, -0.02, 0]}
          />
        </group>
        <group name="Clock" position={[108.56, 89.16, -19.97]}>
          <mesh
            name="Cylinder 19"
            geometry={nodes['Cylinder 19'].geometry}
            material={materials['Cylinder 19 Material']}
            castShadow
            receiveShadow
            position={[114.47, 89.59, -18.47]}
            rotation={[0, -0.02, -1.45]}
            scale={0.09}
          />
          <mesh
            name="Cylinder 20"
            geometry={nodes['Cylinder 20'].geometry}
            material={materials['Cylinder 20 Material']}
            castShadow
            receiveShadow
            position={[108.42, 90.31, -18.57]}
            rotation={[0, -0.02, 0]}
            scale={0.03}
          />
          <mesh
            name="Cylinder 18"
            geometry={nodes['Cylinder 18'].geometry}
            material={materials['Cylinder 18 Material']}
            castShadow
            receiveShadow
            position={[108.42, 94.55, -18.57]}
            rotation={[0, -0.02, 0]}
            scale={0.09}
          />
          <mesh
            name="Cylinder 17"
            geometry={nodes['Cylinder 17'].geometry}
            material={materials['Cylinder 17 Material']}
            castShadow
            receiveShadow
            position={[108.56, 89.16, -20.37]}
            rotation={[1.57, 0, 0.02]}
          />
        </group>
        <group name="Chair" position={[18.48, -25.45, 76.47]}>
          <mesh
            name="Cylinder 16"
            geometry={nodes['Cylinder 16'].geometry}
            material={materials['Chair Base']}
            castShadow
            receiveShadow
            position={[-1.89, -58.32, 75.62]}
            rotation={[Math.PI, -1.26, -Math.PI / 2]}
            scale={[0.78, 0.17, 0.78]}
          />
          <mesh
            name="Cylinder 15"
            geometry={nodes['Cylinder 15'].geometry}
            material={materials['Chair Base']}
            castShadow
            receiveShadow
            position={[39.16, -60.16, 75.65]}
            rotation={[0, -0.84, Math.PI / 2]}
            scale={[0.78, 0.17, 0.78]}
          />
          <mesh
            name="Cylinder 14"
            geometry={nodes['Cylinder 14'].geometry}
            material={materials['Chair Base']}
            castShadow
            receiveShadow
            position={[19.09, -60.16, 56.31]}
            rotation={[0, -0.02, Math.PI / 2]}
            scale={[0.78, 0.17, 0.78]}
          />
          <mesh
            name="Cylinder 13"
            geometry={nodes['Cylinder 13'].geometry}
            material={materials['Chair Base']}
            castShadow
            receiveShadow
            position={[18.39, -60.16, 96.3]}
            rotation={[0, -Math.PI / 9, Math.PI / 2]}
            scale={[0.78, 0.17, 0.78]}
          />
          <mesh
            name="Cube 54"
            geometry={nodes['Cube 54'].geometry}
            material={materials['Chair Base']}
            castShadow
            receiveShadow
            position={[1.73, -56.04, 76.3]}
            rotation={[-Math.PI / 2, 0, 3.12]}
            scale={[0.05, 0.28, 0.36]}
          />
          <mesh
            name="Cube 53"
            geometry={nodes['Cube 53'].geometry}
            material={materials['Chair Base']}
            castShadow
            receiveShadow
            position={[35.73, -56.04, 76.89]}
            rotation={[-Math.PI / 2, 0, 3.12]}
            scale={[0.05, 0.28, 0.36]}
          />
          <mesh
            name="Cube 52"
            geometry={nodes['Cube 52'].geometry}
            material={materials['Chair Base']}
            castShadow
            receiveShadow
            position={[18.72, -52.97, 76.32]}
            rotation={[-Math.PI / 2, 0, 3.12]}
            scale={[0.36, 0.37, 0.36]}
          />
          <mesh
            name="Cube 56"
            geometry={nodes['Cube 56'].geometry}
            material={materials['Chair Base']}
            castShadow
            receiveShadow
            position={[19, -55.64, 60.09]}
            rotation={[-Math.PI / 2, 0, 1.55]}
            scale={[0.36, 0.28, 0.36]}
          />
          <mesh
            name="Cube 55"
            geometry={nodes['Cube 55'].geometry}
            material={materials['Chair Base']}
            castShadow
            receiveShadow
            position={[18.43, -55.64, 93.14]}
            rotation={[-Math.PI / 2, 0, 1.55]}
            scale={[0.36, 0.28, 0.36]}
          />
          <mesh
            name="Cube 51"
            geometry={nodes['Cube 51'].geometry}
            material={materials['Chair Base']}
            castShadow
            receiveShadow
            position={[18.72, -52.97, 76.6]}
            rotation={[-Math.PI / 2, 0, 1.55]}
            scale={[0.36, 0.28, 0.36]}
          />
          <mesh
            name="Cylinder 12"
            geometry={nodes['Cylinder 12'].geometry}
            material={materials['Cylinder 12 Material']}
            castShadow
            receiveShadow
            position={[18.56, -42.73, 76.25]}
            rotation={[0, -0.02, Math.PI]}
            scale={[0.13, 0.22, 0.13]}
          />
          <mesh
            name="Cube 50"
            geometry={nodes['Cube 50'].geometry}
            material={materials.Chair}
            castShadow
            receiveShadow
            position={[18.33, -30.18, 76.26]}
            rotation={[-Math.PI / 2, 0, 1.55]}
            scale={[1.37, 1.37, 0.62]}
          />
          <mesh
            name="Cube 49"
            geometry={nodes['Cube 49'].geometry}
            material={materials['Cube 49 Material']}
            castShadow
            receiveShadow
            position={[17.42, -18.32, 57.16]}
            rotation={[0, 1.55, 0]}
          />
          <mesh
            name="Cube 48"
            geometry={nodes['Cube 48'].geometry}
            material={materials.Chair}
            castShadow
            receiveShadow
            position={[17.4, 1.45, 58.16]}
            rotation={[0, 1.55, 0]}
          />
        </group>
        <group name=" Coffee Cup" position={[-37.51, -2.92, 35.73]}>
          <mesh
            name="Torus"
            geometry={nodes.Torus.geometry}
            material={materials['Torus Material']}
            castShadow
            receiveShadow
            position={[-34.07, -3.08, 36]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            name="Cylinder 11"
            geometry={nodes['Cylinder 11'].geometry}
            material={materials['Cylinder 11 Material']}
            castShadow
            receiveShadow
            position={[-35.99, -2.27, 3.73]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.29, 0.52, 0.29]}
          />
        </group>
        <group name="Computer" position={[-61.84, 8.2, 80.6]}>
          <group name="Keyboard" position={[-41.67, -9.18, 83.02]}>
            <mesh
              name="Cube 46"
              geometry={nodes['Cube 46'].geometry}
              material={materials['Cube 46 Material']}
              castShadow
              receiveShadow
              position={[56.05, -8.8, -10]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 45"
              geometry={nodes['Cube 45'].geometry}
              material={materials['Cube 45 Material']}
              castShadow
              receiveShadow
              position={[56.05, -8.8, -15.18]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 44"
              geometry={nodes['Cube 44'].geometry}
              material={materials['Cube 44 Material']}
              castShadow
              receiveShadow
              position={[61.04, -8.8, -15.18]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 43"
              geometry={nodes['Cube 43'].geometry}
              material={materials['Cube 43 Material']}
              castShadow
              receiveShadow
              position={[65.28, -8.8, -15.18]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 42"
              geometry={nodes['Cube 42'].geometry}
              material={materials['Cube 42 Material']}
              castShadow
              receiveShadow
              position={[68.71, -8.8, -15.18]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 82"
              geometry={nodes['Cube 82'].geometry}
              material={materials['Cube 82 Material']}
              castShadow
              receiveShadow
              position={[68.83, -8.8, -10.28]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 41"
              geometry={nodes['Cube 41'].geometry}
              material={materials['Cube 41 Material']}
              castShadow
              receiveShadow
              position={[72.06, -8.8, -15.18]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 40"
              geometry={nodes['Cube 40'].geometry}
              material={materials['Cube 40 Material']}
              castShadow
              receiveShadow
              position={[75.59, -8.8, -15.18]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 39"
              geometry={nodes['Cube 39'].geometry}
              material={materials['Cube 39 Material']}
              castShadow
              receiveShadow
              position={[79.31, -8.8, -15.18]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 38"
              geometry={nodes['Cube 38'].geometry}
              material={materials['Cube 38 Material']}
              castShadow
              receiveShadow
              position={[82.95, -8.8, -14.38]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 37"
              geometry={nodes['Cube 37'].geometry}
              material={materials['Cube 37 Material']}
              castShadow
              receiveShadow
              position={[86.66, -8.8, -15.14]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 36"
              geometry={nodes['Cube 36'].geometry}
              material={materials['Cube 36 Material']}
              castShadow
              receiveShadow
              position={[86.66, -8.8, -19.27]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 35"
              geometry={nodes['Cube 35'].geometry}
              material={materials['Cube 35 Material']}
              castShadow
              receiveShadow
              position={[82.71, -8.8, -19.27]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 34"
              geometry={nodes['Cube 34'].geometry}
              material={materials['Cube 34 Material']}
              castShadow
              receiveShadow
              position={[79.2, -8.8, -19.27]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 33"
              geometry={nodes['Cube 33'].geometry}
              material={materials['Cube 33 Material']}
              castShadow
              receiveShadow
              position={[75.59, -8.8, -19.27]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 32"
              geometry={nodes['Cube 32'].geometry}
              material={materials['Cube 32 Material']}
              castShadow
              receiveShadow
              position={[72, -8.8, -19.27]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 31"
              geometry={nodes['Cube 31'].geometry}
              material={materials['Cube 31 Material']}
              castShadow
              receiveShadow
              position={[68.6, -8.8, -19.27]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 30"
              geometry={nodes['Cube 30'].geometry}
              material={materials['Cube 30 Material']}
              castShadow
              receiveShadow
              position={[65.21, -8.8, -19.27]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 29"
              geometry={nodes['Cube 29'].geometry}
              material={materials['Cube 29 Material']}
              castShadow
              receiveShadow
              position={[60.98, -8.8, -19.27]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 28"
              geometry={nodes['Cube 28'].geometry}
              material={materials['Cube 28 Material']}
              castShadow
              receiveShadow
              position={[54.5, -8.8, -19.27]}
              scale={[0.03, 1.04, 0.07]}
            />
            <mesh
              name="Cube 26"
              geometry={nodes['Cube 26'].geometry}
              material={materials['Cube 26 Material']}
              castShadow
              receiveShadow
              position={[71.67, -10.05, -14.08]}
              scale={[0.45, 1.06, 0.58]}
            />
          </group>
          <mesh
            name="Cylinder 10"
            geometry={nodes['Cylinder 10'].geometry}
            material={materials['Cylinder 10 Material']}
            castShadow
            receiveShadow
            position={[-61.84, -11.89, 81.1]}
            rotation={[-Math.PI / 2, 0, -0.02]}
          />
          <mesh
            name="Cube 21"
            geometry={nodes['Cube 21'].geometry}
            material={materials['Cube 21 Material']}
            castShadow
            receiveShadow
            position={[73.82, -4.76, -29.73]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.45, 1.06, 0.58]}
          />
          <mesh
            name="Cube 20"
            geometry={nodes['Cube 20'].geometry}
            material={materials['Cube 20 Material']}
            castShadow
            receiveShadow
            position={[73.82, 16.61, -28.65]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.06}
          />
          <mesh
            name="Cube 19"
            geometry={nodes['Cube 19'].geometry}
            material={materials['Cube 19 Material']}
            castShadow
            receiveShadow
            position={[73.82, 16.62, -29.64]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.25}
          />
        </group>
        <mesh
          name="Cylinder 22"
          geometry={nodes['Cylinder 22'].geometry}
          material={materials['Cylinder 22 Material']}
          castShadow
          receiveShadow
          position={[100.93, -9.04, -38.44]}
          rotation={[-Math.PI, Math.PI / 2, 0]}
          scale={0.92}
        />
        <mesh
          name="Cylinder 21"
          geometry={nodes['Cylinder 21'].geometry}
          material={materials['Cylinder 21 Material']}
          castShadow
          receiveShadow
          position={[100.93, 17.37, -38.44]}
          rotation={[-Math.PI, Math.PI / 2, 0]}
          scale={1.19}
        />
        <group name="Plant" position={[-56.03, -20.74, 181.61]}>
          <mesh
            name="Cylinder 3"
            geometry={nodes['Cylinder 3'].geometry}
            material={materials['Cylinder 3 Material']}
            castShadow
            receiveShadow
            position={[-56.03, -67.11, 177.87]}
            rotation={[0, Math.PI / 2, 0]}
            scale={1.07}
          />
          <mesh
            name="Cylinder 6"
            geometry={nodes['Cylinder 6'].geometry}
            material={materials['Cylinder 6 Material']}
            castShadow
            receiveShadow
            position={[-56.54, -20.98, 164.61]}
            rotation={[-0.28, 1.06, 3.04]}
            scale={0.51}
          />
          <mesh
            name="Cylinder 8"
            geometry={nodes['Cylinder 8'].geometry}
            material={materials['Cylinder 8 Material']}
            castShadow
            receiveShadow
            position={[-60.2, -33.29, 193.88]}
            rotation={[-2.62, 1.24, 0]}
            scale={0.51}
          />
          <mesh
            name="Cylinder 9"
            geometry={nodes['Cylinder 9'].geometry}
            material={materials['Cylinder 9 Material']}
            castShadow
            receiveShadow
            position={[-50.57, -33.51, 162.4]}
            rotation={[-0.33, 0.34, 2.99]}
            scale={0.51}
          />
          <mesh
            name="Cylinder 7"
            geometry={nodes['Cylinder 7'].geometry}
            material={materials['Cylinder 7 Material']}
            castShadow
            receiveShadow
            position={[-61.61, -19.2, 186.79]}
            rotation={[-2.98, Math.PI / 2, 0]}
            scale={0.51}
          />
          <mesh
            name="Cylinder 5"
            geometry={nodes['Cylinder 5'].geometry}
            material={materials['Cylinder 5 Material']}
            castShadow
            receiveShadow
            position={[-61.61, -12.85, 174.3]}
            rotation={[3.05, Math.PI / 2, 0]}
            scale={0.51}
          />
          <mesh
            name="Cylinder 2"
            geometry={nodes['Cylinder 2'].geometry}
            material={materials['Cylinder 2 Material']}
            castShadow
            receiveShadow
            position={[-56.03, -54.88, 177.87]}
            rotation={[0, Math.PI / 2, 0]}
          />
        </group>
        <group name="Bed" position={[143.08, -16.93, 58.06]}>
          <mesh
            name="Cube 17"
            geometry={nodes['Cube 17'].geometry}
            material={materials['Cube 17 Material']}
            castShadow
            receiveShadow
            position={[145.4, -37.43, 22.64]}
            rotation={[-Math.PI / 2, 0, 1.55]}
            scale={1.07}
          />
          <mesh
            name="Cube 16"
            geometry={nodes['Cube 16'].geometry}
            material={materials['Cube 16 Material']}
            castShadow
            receiveShadow
            position={[147.35, -13.27, 0.73]}
            rotation={[-0.68, -0.02, 1.56]}
            scale={[0.64, 0.64, 0.98]}
          />
          <group name="Empty Object 2" position={[143.06, -16.93, 54.46]}>
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials['Bed Wood']}
              castShadow
              receiveShadow
              position={[173.88, -17.93, 177.85]}
              rotation={[0, 0, Math.PI / 2]}
              scale={2.18}
            />
            <mesh
              name="Cube 15"
              geometry={nodes['Cube 15'].geometry}
              material={materials['Bed Wood']}
              castShadow
              receiveShadow
              position={[89.36, -22.11, 166]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Cube 151"
              geometry={nodes['Cube 151'].geometry}
              material={materials['Bed Wood']}
              castShadow
              receiveShadow
              position={[89.39, -22.11, 89.77]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Cube 12"
              geometry={nodes['Cube 12'].geometry}
              material={materials['Bed Wood']}
              castShadow
              receiveShadow
              position={[89.38, -23.69, 128.55]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Cube 14"
              geometry={nodes['Cube 14'].geometry}
              material={materials['Bed Wood']}
              castShadow
              receiveShadow
              position={[173.97, -42.39, 177.84]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[1.62, 1.62, 1.43]}
            />
            <mesh
              name="Cube 121"
              geometry={nodes['Cube 121'].geometry}
              material={materials['Cube 121 Material']}
              castShadow
              receiveShadow
              position={[99.39, -46.25, 179.3]}
              scale={1.62}
            />
          </group>
          <mesh
            name="Cube 152"
            geometry={nodes['Cube 152'].geometry}
            material={materials['Cube 152 Material']}
            castShadow
            receiveShadow
            position={[87.54, -36.52, 179.3]}
            scale={[1.73, 1.62, 1.7]}
          />
          <mesh
            name="Cube 74"
            geometry={nodes['Cube 74'].geometry}
            material={materials['Cube 74 Material']}
            castShadow
            receiveShadow
            position={[99.39, -32.4, 179.3]}
            scale={[1.62, 1.62, 1.64]}
          />
        </group>
        <group name="Table" position={[-52.43, -37.39, 81.58]}>
          <mesh
            name="Cube 11"
            geometry={nodes['Cube 11'].geometry}
            material={materials['Cube 11 Material']}
            castShadow
            receiveShadow
            position={[128.77, -49.75, -43.51]}
            scale={[0.68, 10.27, 0.86]}
          />
          <mesh
            name="Cube 10"
            geometry={nodes['Cube 10'].geometry}
            material={materials['Cube 10 Material']}
            castShadow
            receiveShadow
            position={[17.57, -49.75, -43.51]}
            scale={[0.68, 10.27, 0.86]}
          />
          <mesh
            name="Cube 111"
            geometry={nodes['Cube 111'].geometry}
            material={materials['Cube 111 Material']}
            castShadow
            receiveShadow
            position={[128.77, -49.75, 2.48]}
            scale={[0.68, 10.27, 0.86]}
          />
          <mesh
            name="Cube 9"
            geometry={nodes['Cube 9'].geometry}
            material={materials['Cube 9 Material']}
            castShadow
            receiveShadow
            position={[17.57, -49.75, 2.48]}
            scale={[0.68, 10.27, 0.86]}
          />
          <mesh
            name="Cube 8"
            geometry={nodes['Cube 8'].geometry}
            material={materials['Cube 8 Material']}
            castShadow
            receiveShadow
            position={[73.01, -12.22, -19.92]}
            scale={1.62}
          />
        </group>
        <group name="Books" position={[-0.09, 51.99, -15.98]}>
          <mesh
            name="Cube 23"
            geometry={nodes['Cube 23'].geometry}
            material={materials['Cube 23 Material']}
            castShadow
            receiveShadow
            position={[170.74, 59.13, 43.78]}
            rotation={[-0.12, 0, Math.PI / 2]}
            scale={[6.63, 1.62, 0.07]}
          />
          <mesh
            name="Cube 24"
            geometry={nodes['Cube 24'].geometry}
            material={materials['Cube 24 Material']}
            castShadow
            receiveShadow
            position={[170.74, 59.13, 34.95]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[6.63, 1.62, 0.07]}
          />
          <mesh
            name="Cube 22"
            geometry={nodes['Cube 22'].geometry}
            material={materials['Cube 22 Material']}
            castShadow
            receiveShadow
            position={[170.74, 59.13, 38.63]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[6.63, 1.62, 0.07]}
          />
          <mesh
            name="Cube 58"
            geometry={nodes['Cube 58'].geometry}
            material={materials.Wood}
            castShadow
            receiveShadow
            position={[173.69, 43.06, 23.56]}
            rotation={[0, 0, 0.91]}
            scale={[1.62, 1.62, 0.18]}
          />
          <mesh
            name="Cube 57"
            geometry={nodes['Cube 57'].geometry}
            material={materials.Wood}
            castShadow
            receiveShadow
            position={[173.69, 43.06, 50.8]}
            rotation={[0, 0, 0.91]}
            scale={[1.62, 1.62, 0.18]}
          />
          <mesh
            name="Cube 18"
            geometry={nodes['Cube 18'].geometry}
            material={materials['Wood 2']}
            castShadow
            receiveShadow
            position={[173.36, 46.83, 38.63]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[1.62, 1.62, 1.43]}
          />
        </group>
        <group name="Sticky Notes" position={[-79.67, 7.35, 119.99]}>
          <mesh
            name="Cube 73"
            geometry={nodes['Cube 73'].geometry}
            material={materials['Cube 73 Material']}
            castShadow
            receiveShadow
            position={[31.4, 12.08, -46.57]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[0.37, 0.03, 0.37]}
          />
          <mesh
            name="Cube 72"
            geometry={nodes['Cube 72'].geometry}
            material={materials['Cube 72 Material']}
            castShadow
            receiveShadow
            position={[36.85, 2.61, -47.07]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[0.37, 0.03, 0.37]}
          />
        </group>
        <group name="Walls" position={[52.9, 40.95, 93.04]}>
          <mesh
            name="Cube 79"
            geometry={nodes['Cube 79'].geometry}
            material={materials.Concrete}
            castShadow
            receiveShadow
            position={[149.67, 89.92, -18.44]}
            rotation={[Math.PI / 6, 0, 0]}
          />
          <mesh
            name="Cube 80"
            geometry={nodes['Cube 80'].geometry}
            material={materials.Concrete}
            castShadow
            receiveShadow
            position={[55.55, 140.09, 10.42]}
            rotation={[Math.PI / 6, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube 78"
            geometry={nodes['Cube 78'].geometry}
            material={materials.Concrete}
            castShadow
            receiveShadow
            position={[-24.85, 89.96, -18.54]}
            rotation={[Math.PI / 6, 0, 0]}
          />
          <mesh
            name="Cube 77"
            geometry={nodes['Cube 77'].geometry}
            material={materials.Concrete}
            castShadow
            receiveShadow
            position={[70, -30.21, -54.18]}
          />
          <mesh
            name="Shape"
            geometry={nodes.Shape.geometry}
            material={materials.Concrete}
            castShadow
            receiveShadow
            position={[188.72, -64.65, -37.92]}
            rotation={[0, -0.02, 0]}
          />
          <mesh
            name="Wall"
            geometry={nodes.Wall.geometry}
            material={materials.Wall}
            castShadow
            receiveShadow
            position={[188.4, -64.65, -21.28]}
            rotation={[0, -0.02, 0]}
          />
          <mesh
            name="Cube 5"
            geometry={nodes['Cube 5'].geometry}
            material={materials.Wall}
            castShadow
            receiveShadow
            position={[49, 142.05, 16.7]}
            rotation={[Math.PI / 6, 0, Math.PI / 2]}
          />
          <mesh
            name="Cube 4"
            geometry={nodes['Cube 4'].geometry}
            material={materials.Wall}
            castShadow
            receiveShadow
            position={[142.08, 90.05, -13.22]}
            rotation={[Math.PI / 6, 0, 0]}
          />
          <mesh
            name="Cube 3"
            geometry={nodes['Cube 3'].geometry}
            material={materials.Wall}
            castShadow
            receiveShadow
            position={[-25.65, 89.15, -13.65]}
            rotation={[Math.PI / 6, 0, 0]}
          />
          <mesh
            name="Cube 7"
            geometry={nodes['Cube 7'].geometry}
            material={materials.Wall}
            castShadow
            receiveShadow
            position={[181.1, -20.5, -12.57]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1, 1, 0.32]}
          />
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.Wall}
            castShadow
            receiveShadow
            position={[61.5, -20.5, -48.5]}
          />
        </group>
        <group
          name="Window"
          position={[2086.37, 580.3, -1201.83]}
          rotation={[Math.PI / 6, 0, Math.PI / 2]}
          scale={[0.2, 0.12, 0.04]}
        >
          <mesh
            name="Rectangle 20"
            geometry={nodes['Rectangle 20'].geometry}
            material={materials['Rectangle 20 Material']}
            castShadow
            receiveShadow
            position={[1957.55, 544.77, -1178.08]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[2.86, 1, 1]}
          />
          <mesh
            name="Cube 461"
            geometry={nodes['Cube 461'].geometry}
            material={materials['Cube 461 Material']}
            castShadow
            receiveShadow
            position={[1979.15, 567.89, -1188.75]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.78, 0.17, 0.34]}
          />
          <group name="Empty Object1" position={[1973.2, 572.09, -1196.01]} scale={[1.63, 2.18, 0.2]}>
            <mesh
              name="Mar_Window"
              geometry={nodes.Mar_Window.geometry}
              material={materials['Mar_Window Material']}
              castShadow
              receiveShadow
              position={[2819.45, 573.39, -628.56]}
              rotation={[-Math.PI / 2, -Math.PI / 4, -Math.PI]}
            />
          </group>
          <group name="Window1" position={[1973.2, 572.09, -1268.27]} scale={[1.9, 2.54, 1]}>
            <mesh
              name="Mar_Window1"
              geometry={nodes.Mar_Window1.geometry}
              material={materials['Mar_Window1 Material']}
              castShadow
              receiveShadow
              position={[2819.45, 573.39, -628.56]}
              rotation={[-Math.PI / 2, -Math.PI / 4, -Math.PI]}
            />
          </group>
        </group>
        <group name="Floor" position={[52.4, -67.18, 95.72]}>
          <mesh
            name="Floor Surface"
            geometry={nodes['Floor Surface'].geometry}
            material={materials.Floor}
            castShadow
            receiveShadow
            position={[61.24, -65.16, 67.52]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Wood"
            geometry={nodes.Wood.geometry}
            material={materials['Wood Material']}
            castShadow
            receiveShadow
            position={[61.24, -67.6, 67.52]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Concrete"
            geometry={nodes.Concrete.geometry}
            material={materials.Concrete}
            castShadow
            receiveShadow
            position={[61.24, -79.36, 67.52]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <OrthographicCamera
          name="Default Camera"
          makeDefault={true}
          zoom={1.51}
          far={100000}
          near={-50000}
          position={[565.14, 375.08, 723.2]}
          rotation={[-0.52, 0.6, 0.31]}
        />
      </group>
    </>
  )
}
